/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package virtual_classroom;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author home
 */
public class Exam extends javax.swing.JFrame {
        static Socket client;
        static BufferedReader in;
        static PrintWriter out;
        static String s3 = "";

    /**
     * Creates new form Exam
     */
    public Exam(String s, String t) {
        initComponents();
        jLabel1.setText(s);
        jLabel2.setText(t);
  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1019, 640));
        setPreferredSize(new java.awt.Dimension(1019, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Harrington", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 41, 219, 37);

        jLabel2.setFont(new java.awt.Font("Harrington", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 40, 258, 37);

        jLabel3.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("Question :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 120, 113, 35);

        jScrollPane1.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(281, 118, 708, 74);

        jLabel4.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(281, 236, 708, 27);

        jLabel5.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(281, 294, 708, 23);

        jLabel6.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(281, 348, 708, 23);

        jLabel7.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(281, 402, 708, 23);

        jLabel8.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("A.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(197, 236, 23, 27);

        jLabel9.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText("B.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(198, 294, 22, 23);

        jLabel10.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("C.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(200, 348, 20, 23);

        jLabel11.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 153));
        jLabel11.setText("D.");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(198, 402, 22, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 153));
        jRadioButton1.setText("A");
        jRadioButton1.setOpaque(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(281, 476, 43, 37);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 153));
        jRadioButton2.setText("B");
        jRadioButton2.setOpaque(false);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(443, 476, 43, 37);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 153));
        jRadioButton3.setText("C");
        jRadioButton3.setOpaque(false);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(634, 476, 41, 37);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 153));
        jRadioButton4.setText("D");
        jRadioButton4.setOpaque(false);
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(820, 476, 43, 37);

        jButton1.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Next Question");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 550, 190, 33);

        jButton2.setFont(new java.awt.Font("Harrington", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 30, 190, 33);

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/curves-blues-curves-backgrounds-powerpoint.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1020, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
             
             if(jRadioButton1.isSelected())
                 s3=jRadioButton1.getText();
             if(jRadioButton2.isSelected())
                 s3=jRadioButton2.getText();
             if(jRadioButton3.isSelected())
                 s3=jRadioButton3.getText();
             if(jRadioButton4.isSelected())
                 s3=jRadioButton4.getText();
             

             out.println(s3);
             String str = in.readLine();
             if(!str.equals("complete"))
             {
                 jTextArea1.setText(str);
                 jLabel4.setText(in.readLine());
                 jLabel5.setText(in.readLine());
                 jLabel6.setText(in.readLine());
                 jLabel7.setText(in.readLine());
                    
             }
             else
             {
                 JOptionPane.showMessageDialog(this, "Your Test Score is: "+in.readLine(), "Test Result!!!", JOptionPane.INFORMATION_MESSAGE);
                 this.setVisible(false);
             }
             
             
   }
        catch(IOException | HeadlessException e)
        {
            System.out.println(e);
        }      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                 try {
             client=new Socket("localhost",2014);
             in=new BufferedReader(new InputStreamReader(client.getInputStream()));
             out=new PrintWriter(client.getOutputStream(),true);
             out.println("AttemptTest");
           
             out.println(jLabel1.getText());
             out.println(jLabel2.getText());
                                
             jTextArea1.setText(in.readLine());
             jLabel4.setText(in.readLine());
             jLabel5.setText(in.readLine());
             jLabel6.setText(in.readLine());
             jLabel7.setText(in.readLine());
                     
              
        }
        catch(IOException | HeadlessException e)
        {
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam("","").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
