/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package virtual_classroom;

import java.awt.HeadlessException;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author home
 */
public class SelectFile extends javax.swing.JFrame {
   static String filename1, fname, subject;
   static DataInputStream fromSocket;
   static DataOutputStream toSocket;
    /**
     * Creates new form SelectFile
     */
    public SelectFile(String s) {
        subject = s;
        initComponents();
        setLocation(100,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select File");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("Select your file...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(59, 79, 349, 39);

        jTextField1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(33, 149, 400, 35);

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 150, 155, 40);

        jButton2.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(115, 270, 190, 40);

        jButton3.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton3.setText("Sign out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(515, 28, 152, 37);

        jButton5.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton5.setText("Go Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(500, 270, 155, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/ss.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 2, 700, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser choose=new JFileChooser();
        FileNameExtensionFilter f2=new FileNameExtensionFilter("Documents","txt","doc","docx");
        choose.addChoosableFileFilter(f2);
        choose.setFileFilter(f2);
        choose.showOpenDialog(null);
        File f1=choose.getSelectedFile();
        filename1=f1.getAbsolutePath(); 
        System.out.println(filename1);
        fname=f1.getName();
        System.out.println(fname);
        jTextField1.setText(filename1); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home h=new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Teacher_1 t=new Teacher_1();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed
         public void chararray(char r[])
    {
        try {
            for(int i=0;i<r.length;i++)
            {
                toSocket.writeChar(r[i]);
            }
            toSocket.writeChar('$');
        }
        catch (IOException ex) {
                Logger.getLogger(SelectFile.class.getName()).log(Level.SEVERE, null, ex);
         }
    }  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
        if(!(fname.contains(".txt")||fname.contains(".doc")||fname.contains(".docx")||fname.contains(".jpg")||fname.contains(".png")))
            JOptionPane.showMessageDialog(this, "Please select a text or word file. Other formats are not supported","Invalid File Type", JOptionPane.ERROR_MESSAGE);
        else{
        Socket client=new Socket("localhost",2015);
        fromSocket = new DataInputStream(client.getInputStream());
        toSocket = new DataOutputStream(client.getOutputStream());
         chararray("FileUpload".toCharArray());
         chararray(fname.toCharArray());
         chararray(subject.toCharArray());
         DataInputStream fromFile = new DataInputStream(new FileInputStream(filename1));
          byte[] b = new byte[16777216];
            int s = fromFile.available();
            byte h = 0;
            int i=0,k=0;
            while(s!=0)
            {
                h=fromFile.readByte();
                k=i;
                b[i++]=h;
                System.out.print((char)b[k]);
                s--;
            }
            toSocket.writeInt(i);
            for(int u =0;u<i;u++)
                toSocket.writeByte(b[u]);
        fromFile.close();
        
        char a [] = new char[20];
        int j =0, o =0;
        while((a[j++]=fromSocket.readChar())!='$')    o++;
        char t[] = new char[o];
        System.arraycopy(a, 0, t, 0, o); 
        String status = new String(t);
        System.out.print(status);
        if(status.equals("UploadUnsuccessful"))
            JOptionPane.showMessageDialog(this, "File couldn't be uploaded. Thefile format was not supported or the file was already present ", "Upload Unsuccessful", JOptionPane.ERROR_MESSAGE);
        if(status.equals("UploadSuccessful"))
            JOptionPane.showMessageDialog(this, "File has been uploaded", "Upload Successful", JOptionPane.OK_OPTION);
        chararray("UploadComplete".toCharArray());
        }
}
catch(HeadlessException | IOException e)
{
    chararray("UploadUnsuccessful".toCharArray());      
    e.printStackTrace();
}
    
          
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectFile("").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private DataInputStream DataInputStream(String filename1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
