/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package virtual_classroom;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        setLocation(200,50); 
        initComponents();
        jLabel12.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NAME");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 70, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FATHER'S NAME");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 120, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("MOTHER'S NAME");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 170, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("CLASS");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 220, 210, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ROLL NO.");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 270, 210, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("SCHOLAR NO.");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 320, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("CONTACT NO.");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 370, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("EMAIL ID");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 420, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("PASSWORD");
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 470, 210, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("CONFIRM PASSWORD");
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 520, 210, 30);

        jTextField1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(330, 70, 120, 30);

        jTextField2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(470, 70, 100, 30);

        jTextField3.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField3.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(590, 70, 200, 30);

        jTextField4.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField4.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(330, 120, 240, 30);

        jTextField5.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField5);
        jTextField5.setBounds(330, 170, 240, 30);

        jTextField6.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField6.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(330, 220, 240, 30);

        jTextField7.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField7.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField7);
        jTextField7.setBounds(330, 270, 240, 30);

        jTextField8.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField8.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jTextField8);
        jTextField8.setBounds(330, 320, 240, 30);

        jTextField10.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField10.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel1.add(jTextField10);
        jTextField10.setBounds(330, 370, 238, 32);

        jTextField11.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jTextField11.setPreferredSize(new java.awt.Dimension(65, 30));
        jPanel1.add(jTextField11);
        jTextField11.setBounds(330, 420, 238, 30);

        jPasswordField1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jPasswordField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(330, 470, 240, 30);

        jPasswordField2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jPasswordField2.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(330, 520, 240, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 600, 110, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("RESET");
        jButton2.setPreferredSize(new java.awt.Dimension(90, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 600, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Passwords do not match!!");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(600, 524, 200, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/green.jpg"))); // NOI18N
        jLabel11.setText("Passwords do not match");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 920, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel12.setVisible(false);
        if(Arrays.equals(jPasswordField1.getPassword(), jPasswordField2.getPassword()))
        {
        try {
             Socket client;
             BufferedReader in;
             PrintWriter out;
             client=new Socket("localhost",2014);
             in=new BufferedReader(new InputStreamReader(client.getInputStream()));
             out=new PrintWriter(client.getOutputStream(),true);
             out.println("register");
             out.println(jTextField1.getText());
             out.println(jTextField2.getText());
             out.println(jTextField3.getText());
             out.println(jTextField4.getText());
             out.println(jTextField5.getText());
             out.println(jTextField6.getText());
             out.println(jTextField7.getText());
             out.println(jTextField8.getText());
             out.println(jTextField10.getText());
             out.println(jTextField11.getText());
             String s = new String(jPasswordField1.getPassword());
             out.println(s);
            
             String ss = in.readLine();
             if(ss.equals("error"))
             {
                 JOptionPane.showMessageDialog(this,"Please fill all information correctly","EXCEPTION",JOptionPane.ERROR_MESSAGE);
             }
             else if(ss.equals("complete"))
             {
                 JOptionPane.showMessageDialog(this,"Your registration is complete. Your\nLoginID is: "+jTextField11.getText()+"\nPasswor: "+s+"\nNow you can login.","Registration Successful",JOptionPane.ERROR_MESSAGE);
                 StudentLogin sl = new StudentLogin(); 
                 sl.setVisible(true);
                 this.dispose();
             }
        }
        catch(IOException | HeadlessException e)
        {
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Please fill all information correctly","EXCEPTION",JOptionPane.ERROR_MESSAGE);
        }
        }
        else  jLabel12.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
