/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package virtual_classroom;

import java.awt.HeadlessException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static virtual_classroom.SelectFile.filename1;

/**
 *
 * @author hp
 */
public final class Study extends javax.swing.JFrame {
    String p,s,t;
    static Socket client;
    static DataInputStream fromSocket, fromFile;
    static DataOutputStream toSocket, toFile;
    
    public void chararray(char r[])
    {
        try {
            for(int i=0;i<r.length;i++)
            {
                toSocket.writeChar(r[i]);
            }
            toSocket.writeChar('$');
        }
        catch (IOException ex) {
                Logger.getLogger(Study.class.getName()).log(Level.SEVERE, null, ex);
         }
    }  
    char[] read()
   {
       char b[]=new char[16777216];
       int i = 0;
        try { 
              while((b[i]=fromSocket.readChar())!='$')
                i++;
            } catch (IOException ex) {
            Logger.getLogger(Study.class.getName()).log(Level.SEVERE, null, ex);
        }
        char a[] = new char[i];
        for(int j=0;j<i;j++)
        {
            a[j]=b[j];
            System.out.print(a[j]);
        }
        return a;
   }
     
    
    /**    
     * Creates new form Study
     */
    public Study() {
       System.out.println("Start");
        initComponents();
               
        try
        {
            client=new Socket("localhost",2015);
            fromSocket = new DataInputStream(client.getInputStream());
            toSocket = new DataOutputStream(client.getOutputStream());
            System.out.println(0);
            chararray("Initialise".toCharArray());
            System.out.println(0);
            String status = "";
            int i = jTabbedPane2.getTabCount();
            while(!(status=new String(read())).equals("Testdone"))
            {
                for(int k =0;k<i;k++)
                {
                    if(status.equals(jTabbedPane2.getTitleAt(k)))
                    {
                        switch(k)
                        {
                            case 0:
                            Test0.add(new String(read()));
                            break;
                            case 1:
                            Test1.add(new String(read()));
                            break;
                            case 2:
                            Test2.add(new String(read()));
                            break;
                            case 3:
                            Test3.add(new String(read()));
                            break;     
                            case 4:
                            Test4.add(new String(read()));
                            break;
                    }
                    break;
                }
            }
         }
            while(!(status=new String(read())).equals("Filedone"))
            {
                for(int k =0;k<i;k++)
                {
                    if(status.equals(jTabbedPane2.getTitleAt(k)))
                    {
                        switch(k)
                        {
                            case 0:
                            SM0.add(new String(read()));
                            break;
                            case 1:
                            SM1.add(new String(read()));
                            break;
                            case 2:
                            SM2.add(new String(read()));
                            break;
                            case 3:
                            SM3.add(new String(read()));
                            break;     
                            case 4:
                            SM4.add(new String(read()));
                            break;
                    }
                    break;
                }
            }
         }

            
    }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Test0 = new java.awt.List();
        jLabel20 = new javax.swing.JLabel();
        SM0 = new java.awt.List();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Test1 = new java.awt.List();
        SM1 = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SM2 = new java.awt.List();
        jLabel5 = new javax.swing.JLabel();
        Test2 = new java.awt.List();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Test3 = new java.awt.List();
        SM3 = new java.awt.List();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Test4 = new java.awt.List();
        SM4 = new java.awt.List();
        jLabel22 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1300, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tests");
        jPanel12.add(jLabel19);
        jLabel19.setBounds(530, 30, 160, 50);

        Test0.setBackground(new java.awt.Color(255, 204, 204));
        Test0.setFont(new java.awt.Font("Ditnees", 3, 14)); // NOI18N
        Test0.setForeground(new java.awt.Color(255, 0, 0));
        Test0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Test0ItemStateChanged(evt);
            }
        });
        Test0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test0ActionPerformed(evt);
            }
        });
        jPanel12.add(Test0);
        Test0.setBounds(530, 80, 170, 260);

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Study Material");
        jPanel12.add(jLabel20);
        jLabel20.setBounds(350, 30, 160, 50);

        SM0.setBackground(new java.awt.Color(255, 204, 204));
        SM0.setFont(new java.awt.Font("Ditnees", 3, 14)); // NOI18N
        SM0.setForeground(new java.awt.Color(255, 0, 0));
        SM0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SM0ItemStateChanged(evt);
            }
        });
        SM0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SM0ActionPerformed(evt);
            }
        });
        jPanel12.add(SM0);
        SM0.setBounds(340, 80, 160, 260);

        jButton6.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton6.setText("Discussion Board");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton6);
        jButton6.setBounds(990, 30, 270, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/cback.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAutoscrolls(true);
        jPanel12.add(jLabel1);
        jLabel1.setBounds(0, 0, 1638, 1200);

        jTabbedPane2.addTab("Computer", jPanel12);

        jPanel13.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tests");
        jPanel13.add(jLabel8);
        jLabel8.setBounds(570, 110, 190, 40);

        Test1.setBackground(new java.awt.Color(0, 0, 0));
        Test1.setFont(new java.awt.Font("DFKai-SB", 1, 18)); // NOI18N
        Test1.setForeground(new java.awt.Color(0, 204, 204));
        Test1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Test1ItemStateChanged(evt);
            }
        });
        jPanel13.add(Test1);
        Test1.setBounds(570, 150, 190, 210);

        SM1.setBackground(new java.awt.Color(0, 0, 0));
        SM1.setFont(new java.awt.Font("DFKai-SB", 1, 18)); // NOI18N
        SM1.setForeground(new java.awt.Color(0, 204, 204));
        SM1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SM1ItemStateChanged(evt);
            }
        });
        jPanel13.add(SM1);
        SM1.setBounds(350, 150, 190, 210);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Study Material");
        jPanel13.add(jLabel9);
        jLabel9.setBounds(350, 110, 190, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Discussion Board");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton2);
        jButton2.setBounds(970, 43, 290, 50);

        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/MAth.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel13.add(jLabel6);
        jLabel6.setBounds(0, 0, 1800, 780);

        jTabbedPane2.addTab("Maths", jPanel13);

        jPanel14.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Brela-Thin", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/eng2.jpg"))); // NOI18N
        jLabel2.setText("I am Sure you don't want to be like this young man...!!! ");
        jPanel14.add(jLabel2);
        jLabel2.setBounds(80, 60, 1170, 200);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/eng1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setAutoscrolls(true);
        jPanel14.add(jLabel3);
        jLabel3.setBounds(980, 300, 300, 390);

        jLabel4.setFont(new java.awt.Font("Brela-Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tests");
        jPanel14.add(jLabel4);
        jLabel4.setBounds(390, 290, 170, 30);

        SM2.setFont(new java.awt.Font("Aarco1", 1, 14)); // NOI18N
        SM2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SM2ItemStateChanged(evt);
            }
        });
        SM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SM2ActionPerformed(evt);
            }
        });
        jPanel14.add(SM2);
        SM2.setBounds(100, 330, 210, 160);

        jLabel5.setFont(new java.awt.Font("Brela-Thin", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Study Material");
        jPanel14.add(jLabel5);
        jLabel5.setBounds(100, 300, 250, 30);

        Test2.setFont(new java.awt.Font("Aarco1", 1, 14)); // NOI18N
        Test2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Test2ItemStateChanged(evt);
            }
        });
        Test2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test2ActionPerformed(evt);
            }
        });
        jPanel14.add(Test2);
        Test2.setBounds(420, 330, 170, 160);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Brela-Thin", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Discussion Board");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton3);
        jButton3.setBounds(700, 353, 240, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/black.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel14.add(jLabel13);
        jLabel13.setBounds(0, 0, 410, 770);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/black.jpg"))); // NOI18N
        jLabel12.setText("jLabel4");
        jPanel14.add(jLabel12);
        jLabel12.setBounds(340, 0, 1040, 770);

        jTabbedPane2.addTab("English", jPanel14);

        jPanel15.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 204));
        jLabel18.setText(" Ready?? Test your power of Science.");
        jPanel15.add(jLabel18);
        jLabel18.setBounds(20, 20, 470, 40);

        Test3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Test3.setForeground(new java.awt.Color(0, 204, 204));
        Test3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Test3ItemStateChanged(evt);
            }
        });
        Test3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test3ActionPerformed(evt);
            }
        });
        jPanel15.add(Test3);
        Test3.setBounds(30, 70, 370, 160);

        SM3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SM3.setForeground(new java.awt.Color(0, 204, 204));
        SM3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SM3ItemStateChanged(evt);
            }
        });
        SM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SM3ActionPerformed(evt);
            }
        });
        jPanel15.add(SM3);
        SM3.setBounds(30, 330, 370, 160);

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 204));
        jLabel21.setText("Study Material");
        jPanel15.add(jLabel21);
        jLabel21.setBounds(30, 270, 470, 40);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setText("Discussion Board");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton4);
        jButton4.setBounds(40, 523, 350, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/science.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel15.add(jLabel11);
        jLabel11.setBounds(-3, 0, 1400, 630);

        jTabbedPane2.addTab("Science", jPanel15);

        jPanel16.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tests");
        jPanel16.add(jLabel16);
        jLabel16.setBounds(100, 60, 160, 40);

        Test4.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N
        Test4.setForeground(new java.awt.Color(225, 131, 38));
        Test4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Test4ItemStateChanged(evt);
            }
        });
        jPanel16.add(Test4);
        Test4.setBounds(90, 130, 200, 240);

        SM4.setFont(new java.awt.Font("DokChampa", 1, 14)); // NOI18N
        SM4.setForeground(new java.awt.Color(225, 131, 38));
        SM4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SM4ItemStateChanged(evt);
            }
        });
        jPanel16.add(SM4);
        SM4.setBounds(360, 130, 200, 240);

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Study Material");
        jPanel16.add(jLabel22);
        jLabel22.setBounds(370, 60, 160, 40);

        jButton5.setBackground(new java.awt.Color(204, 102, 0));
        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton5.setText("Discussion Board");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton5);
        jButton5.setBounds(960, 63, 260, 40);

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/geography-map-brown-landscape-ppt-backgrounds-powerpoint.jpg"))); // NOI18N
        jPanel16.add(jLabel17);
        jLabel17.setBounds(0, 0, 1330, 630);

        jTabbedPane2.addTab("SocialScience", jPanel16);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 47, 1400, 1670);

        jButton1.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        jButton1.setText("Log Out !!");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1060, 10, 180, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Test4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Test4ItemStateChanged
        t = (String)(Test0.getSelectedItem());
        Exam e = new Exam("SocialScience",t);
        e.setVisible(true);
        //this.setVisible(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_Test4ItemStateChanged

    private void Test3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Test3ItemStateChanged

        t = (String)(Test3.getSelectedItem());
        Exam e = new Exam("Science",t);
        e.setVisible(true);
        //this.setVisible(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_Test3ItemStateChanged

    private void Test2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Test2ItemStateChanged
        s = jTabbedPane2.getTitleAt(2);
        t = (String)(Test2.getSelectedItem());
        Exam e = new Exam(s,t);
        e.setVisible(true);
        //this.setVisible(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_Test2ItemStateChanged

    private void Test1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Test1ItemStateChanged
        s = jTabbedPane2.getTitleAt(1);
        t = (String)(Test1.getSelectedItem());
        Exam e = new Exam(s,t);
        e.setVisible(true);
        //this.setVisible(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_Test1ItemStateChanged

    private void Test0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Test0ActionPerformed

    private void Test0ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Test0ItemStateChanged
        s = jTabbedPane2.getTitleAt(0);
        t = (String)(Test0.getSelectedItem());
        Exam e = new Exam(s,t);
        e.setVisible(true);
//        this.setVisible(false);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_Test0ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home h=new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Test3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Test3ActionPerformed

    private void Test2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Test2ActionPerformed

    private void SM0ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SM0ItemStateChanged
        try{
                  JFileChooser choose=new JFileChooser();
                  choose.showSaveDialog(null);
                  File f1=choose.getSelectedFile();
                  filename1=f1.getAbsolutePath();
                  readFile(jTabbedPane2.getTitleAt(0),SM0.getSelectedItem(),filename1);
            }
            catch(Exception e){
            System.out.println(e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_SM0ItemStateChanged

    private void SM0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SM0ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_SM0ActionPerformed

    private void SM1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SM1ItemStateChanged
        try{
                  JFileChooser choose=new JFileChooser();
                  choose.showSaveDialog(null);
                  File f1=choose.getSelectedFile();
                  filename1=f1.getAbsolutePath();
                  readFile(jTabbedPane2.getTitleAt(1),SM1.getSelectedItem(),filename1);
            }
            catch(Exception e){
            System.out.println(e);
            }         // TODO add your handling code here:
    }//GEN-LAST:event_SM1ItemStateChanged

    private void SM2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SM2ItemStateChanged
                try{
                        JFileChooser choose=new JFileChooser();
                        choose.showSaveDialog(null);
                        System.out.println(0);
                        File f1=choose.getSelectedFile();
                        filename1=f1.getAbsolutePath();
                        readFile(jTabbedPane2.getTitleAt(2),SM2.getSelectedItem(),filename1);
                   }
            catch(Exception e){
            System.out.println(e);
            }// TODO add your handling code here:
    }//GEN-LAST:event_SM2ItemStateChanged

    private void SM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SM2ActionPerformed

    private void SM3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SM3ItemStateChanged
       try{
                  JFileChooser choose=new JFileChooser();
                  choose.showSaveDialog(null);

                  File f1=choose.getSelectedFile();
                  filename1=f1.getAbsolutePath();
                  readFile(jTabbedPane2.getTitleAt(3),SM3.getSelectedItem(),filename1);
            }
            catch(Exception e){
            System.out.println(e);
            }        // TODO add your handling code here:
    
                                       

  // TODO add your handling code here:
    }//GEN-LAST:event_SM3ItemStateChanged
private void readFile(String tab, String fname, String path)
{
   try{
                  client = new Socket("localhost",2015);
                  fromSocket = new DataInputStream(client.getInputStream());
                  toSocket = new DataOutputStream(client.getOutputStream());

                  chararray("FileDownload".toCharArray());
                  chararray(tab.toCharArray());
                  chararray(fname.toCharArray());
                  String extension = new String(read());
                  byte [] b = new byte[fromSocket.readInt()];
                  for(int i = 0;i<b.length;i++)
                    b[i] = fromSocket.readByte();
                  toFile = new DataOutputStream(new FileOutputStream(path+extension));
                  toFile.write(b);
                  toFile.close();
                  String status = new String(read());
                  if(status.equals("DownloadComplete"))
                      JOptionPane.showMessageDialog(this, "Your Download is complete", "Download Successful", JOptionPane.OK_OPTION);
                  else if(status.equals("DownloadUnsuccessful"))
                      JOptionPane.showMessageDialog(this, "Your Download was unsuccessful. Please try  again later", "Download Unsuccessful", JOptionPane.ERROR_MESSAGE);
       }
   catch(IOException | HeadlessException e)
   {
       e.printStackTrace();
   }
 }
    private void SM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SM3ActionPerformed

    private void SM4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SM4ItemStateChanged
        try{
                  
                  JFileChooser choose=new JFileChooser();
                  choose.showSaveDialog(null);
                  File f1=choose.getSelectedFile();
                  filename1=f1.getAbsolutePath();
                  readFile(jTabbedPane2.getTitleAt(4),SM4.getSelectedItem(),filename1);
            }
            catch(Exception e){
            System.out.println(e);
            }// TODO add your handling code here:
    }//GEN-LAST:event_SM4ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try
        { 
            Discussion d = new Discussion("student","Computer");
            d.setVisible(true);// TODO add your handling code here:
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        { 
            Discussion d = new Discussion("student","Maths"); 
            d.setVisible(true);// TODO add your handling code here:
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        { 
            Discussion d = new Discussion("student","Science");       
            d.setVisible(true);// TODO add your handling code here:
        }
        catch(Exception e){
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        { 
            Discussion d = new Discussion("student","English");        
            d.setVisible(true);// TODO add your handling code here:
        }
        catch(Exception e){
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try
        { 
            Discussion d = new Discussion("student","SocialScience");        
            d.setVisible(true);// TODO add your handling code here:
        }
        catch(Exception e){
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Study.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Study.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Study.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Study.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Study().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List SM0;
    private java.awt.List SM1;
    private java.awt.List SM2;
    private java.awt.List SM3;
    private java.awt.List SM4;
    private java.awt.List Test0;
    private java.awt.List Test1;
    private java.awt.List Test2;
    private java.awt.List Test3;
    private java.awt.List Test4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
